### ISSUE TITLE
Cannot open xlsx: Connection refused

### ISSUE THREAD

**Issue by odalet** [sergey-tihon/vscode-openxml-explorer#5]
Each time I right-click an xlsx and choose *Explore OpenXML Package*, the extension complains with:

```
Package '... .xlsx' cannot be opened! Error:
'connect ECONNREFUSED 0.0.0.0:20489'
```

**Comment by sergey-tihon** [comment]
Please update to v0.0.5. It contains a fix for server start + log channel if case of errors.
If it still does not work please tell me what is in the openxml log channel

**Comment by sergey-tihon** [comment]
> Well, it’s a custom in-house format (based on 3MF: https://3mf.io/specification/). Now that I think of it, it’s not OpenXML, but just Open Packaging Convention (OpenXML is a superset of OPC…). Anyway, thanks for the link. I shall try this when I manage to have the extension work on my machine (I posted an issue on your GitHub).

Do you have file in that format that you can share?

**Comment by odalet** [comment]
Concerning the error, it still does not work (though with a different message `Package '/C:/temp/perfs.xlsx' cannot be opened! Error: 'Request failed with status code 500'`). As for the openxml log, the thing is it does not show anything unless I manually kill the `dotnet.exe Server.dll` process that was spawned by VSCode (I suppose the log gets stuck in a buffer unless something else happens or the process is terminated). Well anyway here is what it says (seems connecting to the server is not an issue any more):

```
ExecError: Error: Command failed: dotnet Server.dll

Err: 
Out: Hosting environment: Production
Content root path: c:\Users\odalet\.vscode\extensions\sergey-tihon.openxml-explorer-0.0.5\bin\
Now listening on: http://0.0.0.0:20489
Application started. Press Ctrl+C to shut down.
System.IO.IOException: La syntaxe du nom de fichier, de r�pertoire ou de volume est incorrecte. : 'c:\c:\temp\foo.xlsx'
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.Packaging.ZipPackage..ctor(String path, FileMode packageFileMode, FileAccess packageFileAccess, FileShare share)
   at System.IO.Packaging.Package.Open(String path, FileMode packageMode, FileAccess packageAccess, FileShare packageShare)
   at System.IO.Packaging.Package.Open(String path, FileMode packageMode, FileAccess packageAccess)
   at OpenXmlApi.getPackageInfo(String path) in /Users/sergey/github/vscode-openxml-explorer/src/Server/OpenXmlApi.fs:line 11
   at OpenXmlApi.openXmlApi@52-2.Invoke(Unit unitVar) in /Users/sergey/github/vscode-openxml-explorer/src/Server/OpenXmlApi.fs:line 52
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 386
   at Microsoft.FSharp.Control.AsyncPrimitives.unitAsync@577.Invoke(AsyncActivation`1 ctxt) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 577
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 104
System.IO.IOException: La syntaxe du nom de fichier, de r�pertoire ou de volume est incorrecte. : 'c:\c:\temp\foo.xlsx'
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.Packaging.ZipPackage..ctor(String path, FileMode packageFileMode, FileAccess packageFileAccess, FileShare share)
   at System.IO.Packaging.Package.Open(String path, FileMode packageMode, FileAccess packageAccess, FileShare packageShare)
   at System.IO.Packaging.Package.Open(String path, FileMode packageMode, FileAccess packageAccess)
   at OpenXmlApi.getPackageInfo(String path) in /Users/sergey/github/vscode-openxml-explorer/src/Server/OpenXmlApi.fs:line 11
   at OpenXmlApi.openXmlApi@52-2.Invoke(Unit unitVar) in /Users/sergey/github/vscode-openxml-explorer/src/Server/OpenXmlApi.fs:line 52
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 386
   at Microsoft.FSharp.Control.AsyncPrimitives.unitAsync@577.Invoke(AsyncActivation`1 ctxt) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 577
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 104
```

I'm trying to explore `c:\temp\foo.xlsx` but it seems an additional `C:\` is prepended to the path making it obviously invalid (maybe the underlying logic works on a Linux box though, didn't test). By the way, the path in the error message is weird as well. I suppose my troubles come from this `/` prepended to the full path in '/C:/temp/perfs.xlsx'. This is passed as is to the server then I suppose it thinks it's a (Windows) relative path and then prepends an additional `C:` in order to resolve it... I'd examine what's going one between https://github.com/sergey-tihon/vscode-openxml-explorer/blob/f850117200a1bbcf8eb3b0106cec9205f2974a20/src/extension/Agent.fs#L22 and https://github.com/sergey-tihon/vscode-openxml-explorer/blob/f850117200a1bbcf8eb3b0106cec9205f2974a20/src/Server/OpenXmlApi.fs#L10

----

Concerning the custom format I was talking about, I'm afraid I can't share anything (I'll make sure of it but there's little hope). However, if you are interested, you can play with any `.3mf` file you'll find (as our format is but an extension of `3mf` and fully compatible with it). For example, any file [here](https://github.com/3MFConsortium/3mf-samples) should do! Once again, I got mixed up, these are not OpenXML files but Open Packaging Convention ones. Anyway they still are zip archives made of 'parts' and linked by uris... should be quite similar at a low level.

**Comment by odalet** [comment]
Just tested v0.0.6 and it works! 

I think there still is an issue with how/when the server is launched because I keep having complains of this sort:

```
Err: Unhandled exception. System.IO.IOException: Failed to bind to address http://0.0.0.0:20489: address already in use.
```

But it's nothing more than an annoyance, as the extension works any way (I suppose something is trying to launch the server twice, and the second time fails because the first instance is already running...). So, unless you want to investigate more this one, I'm ok with this issue being closed!

**Comment by sergey-tihon** [comment]
I've release v0.0.7 that dynamically choose port for api server and stop it on extension deactivation. #10 
As a backup solution I added "Restart server" command, so you can restart it if something went wrong.

<img width="653" alt="image" src="https://user-images.githubusercontent.com/1197905/114512058-f6580f80-9c38-11eb-9c8a-a32ffd6889fb.png">

**Comment by odalet** [comment]
Hi, I've tested a bit the new behavior, and now I don't have errors in VSCode, but... I think you are leaking processes:
* When I launch VSCode (with the extension pane visible), the extension initializes and spawns a process (listening to the default 20489 port).
* Then I choose a file to explore, no process is spawned. That is good.
* If I close the package, the process is still alive. I suppose this is normal so that the server can be reused.
* If I choose to restart the server, the previous process is killed and a new one is spawned: good
* But if I close VSCode, the server process is still alive...
* And if I restart VSCode, a second server is spawned listening on 20490...

I have two suggestions to fix that (although I have no idea how easy it is to implement)
* You could try to attach to the last port that was open from the client instead of creating a new server by default - this may imply the server to store (say in a temporary file) its pid and port - and only create a server if non could be found
* Or find some "closing" event of the extension or VSCode itself and kill the server at this time.

**Comment by sergey-tihon** [comment]
Yes, sad but it may happen now.  My primary focus was to fix user experience and then think how can we ensure that we do not leak process. 

> this may imply the server to store (say in a temporary file) its pid and port - and only create a server if non could be found

In this case it is not clean who and when should kill process. Also in the dev loop I need always start newer version of server

> Or find some "closing" event of the extension or VSCode itself and kill the server at this time.

That is exactly an idea and it is implemented https://github.com/sergey-tihon/vscode-openxml-explorer/blob/main/src/extension/extension.fs#L53-L56 but need to investigate why it does not work as expected.
